ecom/cartapp/urls.py
from django.contrib import admin
from django.urls import path,include

from cartapp import views

app_name='cartapp'

urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cartdetail,name="cartdetail"),
    path( 'remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path( 'full_remove/<int:product_id>/',views.full_remove,name='full_remove')
]

ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from  django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shoppingapp.urls')),
    path('search/', include('searchapp.urls')),
    path('cart/', include('cartapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecom/searchapp/urls.py
from django.contrib import admin
from django.urls import path,include

from searchapp import views

app_name='searchapp'
urlpatterns=[
    path('',views.SerchResult,name='SerchResult'),
]

ecom/shoppingapp/urls.py
from django.contrib import admin
from django.urls import path,include

from shoppingapp import views
app_name='shoppingapp'
urlpatterns = [
    path('',views.allProductCategary,name='allproduct'),
    path('<slug:c_slug>/',views.allProductCategary,name="product_by_categary"),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name="productdetail")
]

ecom/cartapp/models.py
from django.db import models

# Create your models here.
from shoppingapp .models import Product
class Cart(models.Model):
    cart_id=models.CharField(max_length=350,blank=True,null=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self. cart_id)

class Cartitem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='Cartitem'
    def sub_total(self):
        return  self.product.price * self.quantity
    def __str__(self):
        return  '{}'.format (self.product)

ecom/searchapp/models.py
from django.db import models

# Create your models here.

ecom/shoppingapp/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
from django.urls import reverse


class Categary(models.Model):
        name=models.CharField(max_length=250,unique=True)
        slug=models.SlugField(max_length=250,unique=True)
        description=models.TextField(blank=True)
        image=models.ImageField(upload_to='categary',blank=True)

        class Meta:
                ordering = ('name', )
                verbose_name = 'categary'
                verbose_name_plural = 'categaries'

        def get_url(self):
          return reverse('shoppingapp:product_by_categary',args=[self.slug])


        def __str__(self):
          return '{}'.format(self.name)

class Product(models.Model):
        name = models.CharField(max_length=250, unique=True)
        slug = models.SlugField(max_length=250, unique=True)
        description = models.TextField(blank=True)
        price=models.DecimalField(max_digits=10,decimal_places=2)
        categary=models.ForeignKey(Categary,on_delete=models.CASCADE)
        image = models.ImageField(upload_to='Product', blank=True)
        stock=models.IntegerField()
        available=models.BooleanField(default=True)
        created=models.DateTimeField(auto_now_add=True)
        updated=models.DateTimeField(auto_now=True)

        def get_url(self):
                return  reverse('shoppingapp:productdetail',args=[self.categary.slug,self.slug])

        class Meta:
                ordering = ('name',)
                verbose_name = 'product'
                verbose_name_plural = 'products'


        def __str__(self):
         return '{}'.format(self.name)

ecom/cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shoppingapp .models import Product
from .models import Cart,Cartitem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
     cart=request.session.session_key
     if not cart:
       cart=request.session.create()
       return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))

    except Cart.DoesNotExist:

        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

    try :

        cartitem=Cartitem.objects.get(product=product,cart=cart)
        if cartitem.quantity < cartitem.product.stock:
         cartitem.quantity +=1
         cartitem.save()

    except Cartitem.DoesNotExist:

        cartitem=Cartitem.objects.create(product=product,quantity=1,cart=cart)
        cartitem.save()

    return redirect('cartapp:cartdetail')

def cartdetail(request,total=0,counter= 0,cartitems=None):

    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cartitems=Cartitem.objects.filter( cart=cart,active=True)

        for cartitem in cartitems:
            total+= (cartitem.product.price * cartitem.quantity)
            counter+= cartitem.quantity

    except ObjectDoesNotExist:

       pass

    return render(request,'cart.html',dict(cartitems=cartitems,total=total,counter=counter))

def cart_remove(request,product_id):

     cart=Cart.objects.get(cart_id=_cart_id(request))
     product=get_object_or_404(Product,id=product_id)
     cartitem=Cartitem.objects.get(product=product,cart=cart)
     if cartitem.quantity > 1:
         cartitem.quantity -=1
         cartitem.save()
     else:
         cartitem.delete()

     return redirect('cartapp:cartdetail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cartitem = Cartitem.objects.get(product=product, cart=cart)
    cartitem.delete()
    return redirect('cartapp:cartdetail')

ecom/searchapp/views.py
from django.db import models
from django.shortcuts import render

from shoppingapp.models import Product
from django.db.models import Q
# Create your models here.
def SerchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query)| Q(description__contains=query))
        return render(request,"search.html",{'query':query,'products':products})

ecom/shoppingapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404

from .models import Categary,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.

def allProductCategary(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Categary,slug=c_slug)
        products_list=Product.objects.all().filter(categary=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)

    paginator=Paginator(products_list,6)

    try:

        page=int(request.GET.get('page','1'))


    except:

        page=1
    try:

         products=paginator.page(page)

    except(EmptyPage,InvalidPage):

       products=paginator.page(paginator.num_pages)

    return  render(request,"categary.html",{'categary':c_page,'products':products})

def proDetail(request,c_slug,product_slug):
     try:
         product=Product.objects.get(categary__slug=c_slug,slug=product_slug)
     except Exception as e:

         raise e

     return render(request,"product.html",{'product':product})

ecom/templates/base.html
{%   load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href=" {% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <script src="https://kit.fontawesome.com/e22ff882ab.js" crossorigin="anonymous"></script>
       <meta name="description" content="{% block metadescription %}"{%endblock%}>
    <title>{%  block title %}{% endblock %}</title>
</head>
<body>

<div class="container">
      {% include 'header.html' %}
     {% include 'navbar.html' %}
     {% block content%}
     {% endblock %}
</div>
     {% include 'footer.html' %}
      <script src= "{% static  'js/popper.min.js'%}"></script>
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <script src="{% static 'js/.slim.min.js'%}"></script>
</body>
</html>

ecom/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   This is the Cartpage. proceed to recvie your items and place your order
{% endblock %}
 {% block title %}
 Cart-Organic store PVT LTD
{% endblock %}
{% block content %}
{% if not cartitems %}
    <div>
    <div class="text-center">
      <br>
        <h1 class="text-center my_title">
            Yor Shopping Cart is Empty
        </h1>
        <br>
        <p class="text-center">
            Pleace click <a href="{% url 'shoppingapp:allproduct' %}">Here</a>To continue
        </p>
    </div>
    </div>
  {% else %}
    <div>
    <div class="text-center">
      <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
    </div>

        <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">

            <table class="table  my_custom_table">

                <thead class="my_custom_thead">
                 <tr>
                     <th colspan="5">
                         Your Items
                     </th>
                 </tr>
                </thead>

                <tbody>
                 {% for cartitem in cartitems %}
                <tr>
                    <td>
                        <a href="cartitem.product.get_absolute_url"><img src="{{ cartitem.product.image.url }}" alt=""  style="width:100px; height: 100px; " class="float-left rounded custom_image"></a>
                    </td >

                    <td class=" text-left">
                        {{ cartitem.product.name }}
                        <br>
                        {{ cartitem.product.id }}
                        <br>
                        ${{ cartitem.product.price }}
                        <br>
                        {{ cartitem.quantity }} x ${{ cartitem }}
                    </td>

                    <td>
                        ${{ cartitem.sub_total }}
                    </td>

                    {% if cartitem.quantity < cartitem.product.stock %}

                        <td>
                        <a href="{% url 'cartapp:add_cart' cartitem.product.id %}" class="custom_a"> <i class="fa-solid fa-plus"></i></a>
                            &nbsp;&nbsp;<a href="{% url 'cartapp:cart_remove' cartitem.product.id %}" class="custom_a "><i class="fa-solid fa-minus"></i></a>
                            &nbsp;&nbsp;<a href="{% url 'cartapp:full_remove' cartitem.product.id %}" class="custom_a "><i class="fa-solid fa-trash"></i></a>
                        </td>

                    {% else %}
                         <td>

                            &nbsp;<a href="{%  url 'cartapp:cart_remove' cartitem.product.id %}" class=" custom_a "> <i class="fa-solid fa-minus"></i></a>
                            &nbsp;<a href="{% url 'cartapp:full_remove' cartitem.product.id %}" class="custom_a "><i class="fa-solid fa-trash"></i></a>
                        </td>
                    {% endif %}

                </tr>

                 {% endfor %}

                </tbody>
            </table>
        </div>

          <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
              <table class="table my_custom_table">
                  <thead class="my_custom_thead">
                  <tr>
                      <th>
                          Check Out
                      </th>
                  </tr>
                  </thead>
                  <tbody>
                  <tr>
                      <td>
                          Please feedback Here........
                      </td>
                  </tr>
                  <tr>
                      <td class="text-left">
                          Your total is : <strong>{{ total }}</strong>

                      </td>
                  </tr>
                  </tbody>
              </table>
              <div><a href="{% url 'shoppingapp:allproduct' %}" class="btn btn-warning ">Make Payment</a>


              <div class="mx-auto">
                  <a href="{% url 'shoppingapp:allproduct' %}" class="btn btn-secondary btn-block my_custom_button"> Continue shopping</a>
              </div>
 </div>
          </div>
    </div>
    </div>
{% endif %}
{% endblock %}

ecom/templates/categary.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if categary %}
    {{Categary.description|truncatewords:155 }}
  {% else %}
   Welcome to Organic Store you can buy different itemssss..........
  {% endif %}
{% endblock %}

 {% block title %}
 {% if categary  %}
  {{ categary.name }}Organic Store
 {% else %}
  See Our New Collections
{% endif %}
{% endblock %}

{% block content %}
{% if categary %}

    <div class="row my_row_class">
        <div class="mx-auto">
        <p>
            <a href="{%  url 'shoppingapp:allproduct' %}"> Our Product Collections</a>
        </p>
        </div>
    </div>


{% endif %}
   <div class="mx-auto">
       {% if categary %}
       <img class="my_image" src="{{categary.image.url}}"alt="{{ categary.name }} " width="1200px" height="350px" size="center">
   </div>
   <br>
<div>
    <h1 class="text-center my_title" > {{ categary.name }}</h1>
    <p class="text-justify">  {{ categary.description }}</p>
</div>
     {% else %}
    <div>
        <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="our product" width="1300px" height="250px">

    </div>
<br>
<div>
   <h1 class="text-center my_title "> Our Products Collections</h1>
    <p class="text-justify">
     Organic foods are grown either by natural means, without chemical fertilizers or obtained from nature. Such farming methods can produce organic foods in a fairly clean and safe manner and are also very beneficial for human health. Organic foods are free from any type of chemical fertilizers and pesticides. In addition, organic fertilizers are used in place of chemical fertilizers and mainly these fertilizers are used only in organic farming.
    </p>
</div>
{% endif %}
    <div class="container">
    <div class="row mx-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  xol-lg-4">
            <div class="card text-center" style="min-width:18rem">
                <a href="{{ product.get_url }}"><img class="card-img-top  my_image" src="{{ product.image.url }}" alt="{{ product.name }}" height="250px">
                </a>
                <div class="card-body">
                   <h4> {{ product.name }}</h4>
                    <p> ${{ product.price }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
            <hr>
    <div class="text-center">
        {%  for pg in products.paginator.page_range %}

           <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>

        {% endfor %}
    </div>
         {% endif%}
    </div>

        <br>
    </div>

{% endblock %}

ecom/templates/footer.html
<div >
    <p class="text-center"> @copy; Organic shop pvt ltd.all rights reserved </p>
</div>

ecom/templates/header.html
{% load static %}
<header>

    <center>
        <a href="{%url 'shoppingapp:allproduct' %}"></a> <img src="{% static 'img/logo.png' %}" alt="logoimage" width="200px">
    </center>

</header>

ecom/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

     <li class="nav-item">
          <a class="nav-link" href="{% url 'shoppingapp:allproduct' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shoppingapp' in request.path %}active{% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shoppingapp:allproduct' %}">Allproducts</a></li>
               {% for cat in links %}
            <li><a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a></li>
                {% endfor %}

          </ul>
        </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cartapp:cartdetail' %}"><i class="fa-solid fa-cart-shopping"></i>{{ itemcount }}</a>
      </li>
    </ul>
   <form class="d-flex" action="{% url 'searchapp:SerchResult' %}" method="get">
          {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
  </div>
</nav>

ecom/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    {{product.description|truncatewords:155 }}


{% endblock %}

 {% block title %}

  {{ product.name }}Organic Store

{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p>
            <a href="{%  url 'shoppingapp:allproduct' %}">Home</a>
            <a href="{{ product.categary.get_url }}">{{ product.categary }} </a>
            {{ product.name }}
        </p>
    </div>
</div>

<br>
   <div class="row">
       <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width: 18rem">
            <img src="{{ product.image.url }}" alt="{{ product.name }} ">
        </div>

            <div >
             <div class=" col-12 col-sm-12 col-md-12 col-lg-6">
               <h1 class="my_prod_title">{{ product.name }}</h1>
               <p> $ {{ product.price }}</p>
               <p class="my_title"> product Description</p>
               <p class="text-justify my_prod_text">{{ product.description}}</p>
               {% if product.stock  <= 0 %}
               <p class="text-justify my_prod_text"><b>Out Of Stock</b></p>
               {% else %}
               <a class="btn btn-secondary" href="{%  url 'cartapp:add_cart' product.id %}"> Add to Cart </a>
               {% endif %}
           </div>
         </div>
       </div>
   </div>
    </div>
{% endblock %}

ecom/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   We have variety products
{% endblock %}
{% block title %}
   Search
{% endblock %}
{% block content %}
 <div>
    <p class="text-cente rmy_search"> You have Searched for<b> "{{ query }}"</b> </p>
</div>
    <div class="container">
     <div class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  xol-lg-4">
            <div class="card text-center" style="min-width: 18rem;">
                <a href="{{ product.get_url }}"><img class="card-img-top  my_image" src="{{ product.image.url }}" alt="{{ product.name }}">
                </a>
                <div class="card-body">
                   <h4> {{ product.name }}</h4>
                    <p> $ {{ product.price }}</p>
                </div>
            </div>
        </div>

        {% empty %}
        <div class="row-mx-auto">
            <p class="text-center rmy_search"> 0 results found</p>
        </div>
        {% endfor %}
     </div>
    </div>
{% endblock %}